server:
  port: 8080
spring:
  application:
    name: "basicLibService"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/biblioteca"
    username: "postgres"
    password: "31p@ssword"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
